version: 2
jobs:
  build:
    
    working_directory: ~/test
  
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/node:6
              environment:
                  CHROME_BIN: "/usr/bin/google-chrome"
    steps:

      - checkout

      - restore_cache:
          key: test-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: test-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/myProject-0.0.1-SNAPSHOT.jar
